$(document).ready(function(e) {
    $('.center_show_img').each(function(){
		$(this).live('mouseover',function(){
			$(this).parent().css({'width':'1280px','height':'242px'});
			$(this).animate({width:'1280px',height:'242px'});
			$(this).siblings('.layer').css({'left':'825px'});
			$(this).siblings().children('p').eq(1).show();
			$(this).siblings().children('img').eq(0).hide();
			if($(this).siblings().attr('class')!='layer'){
				$(this).siblings('.layer').css({'left':'125px'});
			}
		}).live('mouseout',function(){
			$(this).parent().css({'width':'1029px','height':'157px'});
			$(this).animate({width:'1029px',height:'157px'});
			$(this).siblings('.layer').css({'left':'704px'});
			$(this).siblings().children('p').eq(1).hide();
			$(this).siblings().children('img').eq(0).show();
			if($(this).siblings().attr('class')!='layer'){
				$(this).siblings('.layer').css({'left':'0'});
			}
		});	
	})
});