;window.replace=function(){return ''};(function(a){function b(a,b){var d=(/^\w+\:\/\//);((/^\/\/\/?/).test(a)?a=location.protocol+a:!d.test(a)&&"/"!=a.charAt(0)&&(a=(b||"")+a));return (d.test(a)?a:("/"==a.charAt(0)?w:x)+a)}function c(a,b){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b}function g(a,b,d,c){a.onload=a.onreadystatechange=function(){a.readyState&&"complete"!=a.readyState&&"loaded"!=a.readyState||b[d]||(a.onload=a.onreadystatechange=null,c())};a.onerror=function(){try{var a=this.src;cError.logError&&cError.logError(["error",
"[Error loading script - status "+d+"]",0,a],"scriptload-error","normal")}catch(b){}}}function k(a){a.ready=a.finished=!0;for(var b=0;b<a.finished_listeners.length;b++)a.finished_listeners[b]();a.ready_listeners=[];a.finished_listeners=[]}function u(a,b,c,l,k){setTimeout(function(){var f,m=b.real_src,e;if("item"in p){if(!p[0]){setTimeout(arguments.callee,25);return}p=p[0]}f=document.createElement("script");b.type&&(f.type=b.type);b.charset&&(f.charset=b.charset);(k?(t?(a[n]&&q("start script preload: "+
m),c.elem=f,(y?(f.preload=!0,f.onpreload=l):f.onreadystatechange=function(){"loaded"==f.readyState&&l()}),f.src=m):(k&&0==m.indexOf(w)&&a[z]?(e=new XMLHttpRequest,a[n]&&q("start script preload (xhr): "+m),e.onreadystatechange=function(){4==e.readyState&&(e.onreadystatechange=function(){},c.text=e.responseText+"\n//@ sourceURL="+m,l())},e.open("GET",m),e.send()):(a[n]&&q("start script preload (cache): "+m),f.type="text/cache-script",g(f,c,"ready",function(){p.removeChild(f);l()}),f.src=m,p.insertBefore(f,
p.firstChild)))):((A?(a[n]&&q("start script load (ordered async): "+m),f.async=!1):a[n]&&q("start script load: "+m)),g(f,c,"finished",l),f.src=m,p.insertBefore(f,p.firstChild)))},0)}function s(){function G(a,b,c){function f(){null!=h&&(h=null,k(c))}var h;m[b.src].finished||(a[v]||(m[b.src].finished=!0),h=c.elem||document.createElement("script"),b.type&&(h.type=b.type),b.charset&&(h.charset=b.charset),g(h,c,"finished",f),(c.elem?c.elem=null:(c.text?(h.onload=h.onreadystatechange=null,h.text=c.text):h.src=
b.real_src)),p.insertBefore(h,p.firstChild),c.text&&f())}function H(a,c,f,g){var h,d,l=function(){c.ready_cb(c,function(){G(a,c,h)})},e=function(){c.finished_cb(c,f)};c.src=b(c.src,a[B]);c.real_src=c.src+(a[C]?((/\?.*$/).test(c.src)?"&_":"?_")+~~(1E9*Math.random())+"=":"");m[c.src]||(m[c.src]={items:[],finished:!1});d=m[c.src].items;(a[v]||0==d.length?(h=d[d.length]={ready:!1,finished:!1,ready_listeners:[l],finished_listeners:[e]},u(a,c,h,(g?function(){h.ready=!0;for(var a=0;a<h.ready_listeners.length;a++)h.ready_listeners[a]();
h.ready_listeners=[]}:function(){k(h)}),g)):(h=d[0],(h.finished?e():h.finished_listeners.push(e))))}function d(){function a(b,c){h[n]&&q("script preload finished: "+b.real_src);b.ready=!0;b.exec_trigger=c;f()}function b(a,c){h[n]&&q("script execution finished: "+a.real_src);a.ready=a.finished=!0;a.exec_trigger=null;for(var d=0;d<c.scripts.length;d++)if(!c.scripts[d].finished)return;c.finished=!0;f()}function f(){for(;e<g.length;)if("[object Function]"==Object.prototype.toString.call(g[e])){h[n]&&q("$LAB.wait() executing: "+
g[e]);try{g[e++]()}catch(a){h[n]&&D("$LAB.wait() error caught: ",a)}}else{if(!g[e].finished){for(var b=g[e],c=!1,d=0;d<b.scripts.length;d++)b.scripts[d].ready&&b.scripts[d].exec_trigger&&(c=!0,b.scripts[d].exec_trigger(),b.scripts[d].exec_trigger=null);if(c)continue;break}e++}e==g.length&&(k=m=!1)}var d,h=c(l,{}),g=[],e=0,m=!1,k;d={script:function(){for(var f=0;f<arguments.length;f++){var e=arguments[f],l=arguments[f],p=void 0;"[object Array]"==Object.prototype.toString.call(e)||(l=[e]);for(var n=
0;n<l.length;n++){if(!k||!k.scripts)g.push(k={scripts:[],finished:!0});e=l[n];"[object Function]"==Object.prototype.toString.call(e)&&(e=e());e&&("[object Array]"==Object.prototype.toString.call(e)?(p=[].slice.call(e),p.unshift(n,1),[].splice.apply(l,p),n--):("string"==typeof e&&(e={src:e}),e=c(e,{ready:!1,ready_cb:a,finished:!1,finished_cb:b}),k.finished=!1,k.scripts.push(e),H(h,e,k,r&&m),m=!0,h[E]&&d.wait()))}}return d},padScript:function(){var a=(navigator.userAgent.match((/(iPad).*OS\s([\d_]+)/))?
!0:!1),b=arguments;a||(b[0]="");return d.script.apply(null,b)},miniScript:function(){return d.script.apply(null,arguments)},wait:function(){if(0<arguments.length){for(var a=0;a<arguments.length;a++)g.push(arguments[a]);k=g[g.length-1]}else k=!1;f();return d}};return{script:d.script,wait:d.wait,padScript:d.padScript,miniScript:d.miniScript,setOptions:function(a){c(a,h);return d}}}var l={},r=t||I,f=[],m={},e;l[z]=!1;l[E]=!1;l[v]=!1;l[C]=!1;l[n]=!1;l[B]="";return e={setGlobalDefaults:function(a){c(a,
l);return e},setOptions:function(){return d().setOptions.apply(null,arguments)},script:function(){return d().script.apply(null,arguments)},padScript:function(){return d().padScript.apply(null,arguments)},miniScript:function(){return d().miniScript.apply(null,arguments)},wait:function(){return d().wait.apply(null,arguments)},queueScript:function(){f[f.length]={type:"script",args:[].slice.call(arguments)};return e},queueWait:function(){f[f.length]={type:"wait",args:[].slice.call(arguments)};return e},
runQueue:function(){for(var a=e,b=f.length,c;0<=--b;)c=f.shift(),a=a[c.type].apply(null,c.args);return a},noConflict:function(){a.$LAB=F;return e},sandbox:function(){return s()}}}var F=a.$LAB,z="UseLocalXHR",E="AlwaysPreserveOrder",v="AllowDuplicates",C="CacheBust",n="Debug",B="BasePath",x=(/^[^?#]*\//).exec(location.href)[0],w=(/^\w+\:\/\/\/?[^\/]+/).exec(x)[0],p=document.head||document.getElementsByTagName("head"),J=a.opera&&"[object Opera]"==Object.prototype.toString.call(a.opera)||"MozAppearance"in
document.documentElement.style,q=function(){},D=q,r=document.createElement("script"),y="boolean"==typeof r.preload,t=y||r.readyState&&"uninitialized"==r.readyState,A=!t&&!0===r.async,I=!t&&!A&&!J;a.console&&a.console.log&&(a.console.error||(a.console.error=a.console.log),q=function(b){a.console.log(b)},D=function(b,c){a.console.error(b,c)});a.$LAB=s();(function(a,b,c){null==document.readyState&&document[a]&&(document.readyState="loading",document[a](b,c=function(){document.removeEventListener(b,c,
!1);document.readyState="complete"},!1))})("addEventListener","DOMContentLoaded")})(this);"undefined"==typeof window.__uidc_init&&(window.__uidc_init=1*new Date);
(function(){function a(){try{document.documentElement.doScroll("left"),$LAB.isReady=!0}catch(b){setTimeout(a,1)}}if(document.addEventListener)document.addEventListener("DOMContentLoaded",function(){$LAB.isReady=!0},!1),window.addEventListener("load",function(){$LAB.isLoaded=!0},!1);else if(document.attachEvent){window.attachEvent("onload",function(){$LAB.isLoaded=!0});var b;try{b=null==window.frameElement}catch(c){}document.documentElement.doScroll&&b&&setTimeout(a,1)}})();
Array.prototype.isSame=function(a){if(this.length!=a.length)return!1;for(var b=0,c=this.length;b<c;b++)if((this[b]||"").toString()!=(a[b]||"").toString())return!1;return!0};$LAB.errorQueue=[];$errorCollection=[];$ubtErrorQueue=[];
var cError={init:function(){cError.flag=!1;cError.spliter=String.fromCharCode(12);cError.setTimer()},checkIsSent:function(a){for(var b=0,c=$errorCollection.length;b<c;b++)if($errorCollection[b].isSame(a))return!0;$errorCollection.push(a);return!1},setTimer:function(){setInterval(function(){cError.fetchError(!1)},500)}};cError.throwError=new Function("err","throw err;");
cError.fetchError=function(a){if(cError.flag==a)if(0!=$LAB.errorQueue.length){cError.flag=!0;var b=$LAB.errorQueue[0];setTimeout(function(){var a=((/msie (\d+)/i).test(navigator.userAgent)?Error(b.number||0,b.msg+cError.spliter):Error(b.msg+cError.spliter,b.file||"",b.line||0));cError.throwError(a)})}else cError.flag=!1};
cError.logError=function(a,b,c){try{if(0!=arguments.length&&!cError.checkIsSent(a)&&(/^http:\/\//).test(document.URL)){for(var g=a.concat([new Date-window.__uidc_init,document.getElementById("page_id")&&document.getElementById("page_id").value,window.UIMonitor2&&window.UIMonitor2.bi&&window.UIMonitor2.bi.pageview_id||"",document.URL,b||"",c||"","cQuery_121128"]),k=0,u=g.length;k<u;k++)g[k]=(""+g[k]).slice().replace((/,/g),"_");(new (Image)).src="js/similarity?ac=error&data="+encodeURIComponent(g.join(","))+
"&rid="+Math.random();var s={version:"1.0",message:a[1],line:a[2],file:a[3],category:b,framework:"cQuery_110421",time:new Date-window.__uidc_init,repeat:1};("undefined"!=typeof $_bf&&"undefined"!=typeof $_bf.loaded?$_bf.trackError(s,function(){return!0}):$ubtErrorQueue.push(s))}}catch(F){}};cError.init();
window.onerror=function(a,b,c){try{if(cError.flag&&a.slice(-1)==cError.spliter){var g=$LAB.errorQueue.shift();cError.logError(["error",g.msg,g.line,g.file],"outer-error","normal");cError.fetchError(!0)}else cError.logError(["error",a,c,b],"inner-error","normal")}catch(k){}};
function logTimer(){var a=document.getElementById("page_id");if(a)var b=(window.__uidc_init?new Date-window.__uidc_init:-1),c=setInterval(function(){window.UIMonitor2&&window.UIMonitor2.trackLog&&(clearInterval(c),window.UIMonitor2.trackLog(a.value,"jsfiles_complete_load",b))},30)}
(function(){for(var a=document.getElementsByTagName("script")||[],b=(/_bfa\.min\.js/i),c=0;c<a.length;c++)if(b.test(a[c].src))return;if(!window.$_bf){a=new Date;b="?v="+a.getFullYear()+a.getMonth()+"_"+a.getDate()+".js";a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;try{var g="https:"==document.location.protocol}catch(k){g="https:"==document.URL.match((/[^:]+/))+":"}a.src=(g?"js/_bfa.min.js"+b:"js/_bfa.min.js"+
b);g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(a,g)}})();(function(){if("undefined"!=typeof $_bf&&"undefined"!=typeof $_bf.loaded){for(var a=0,b=$ubtErrorQueue.length;a<b;a++)$_bf.trackError($ubtErrorQueue[a],function(){return!0});return!1}setTimeout(arguments.callee,250)})();