var G_adContentConfig = { "allyesId":[{"adid":"27",'link':'http://pages.ctrip.com/commerce/promote/201302/flight/fx/index.html ',
'src': 'http://images3.c-ctrip.com/rk/201306/a580X145.jpg ',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=189&s=27&url=http://pages.ctrip.com/commerce/promote/201302/flight/fx/index.html ',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=189&s=27', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=189&s=27', 
'onloadTrackUrl3rd': '', 
'code': 'success'
},{"adid":"28",'link':'http://iservice.10010.com/oftenInfo.html?menuId=000300030001',
'src': 'http://images3.c-ctrip.com/rk/201308/580_1451.jpg',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=539&s=28&url=http://iservice.10010.com/oftenInfo.html?menuId=000300030001',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=539&s=28', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=539&s=28', 
'onloadTrackUrl3rd': '', 
'code': 'success'
},{"adid":"29",'link':'http://hsnrm.qq.com/',
'src': 'http://images3.c-ctrip.com/rk/201309/ksf580145.png',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=523&s=29&url=http://hsnrm.qq.com/',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=523&s=29', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=523&s=29', 
'onloadTrackUrl3rd': '', 
'code': 'success'
},{"adid":"30",'link':'http://events.ctrip.com/eventsale/Vacation/291.html  ',
'src': 'http://images3.c-ctrip.com/dj/201307/gq_580145.jpg ',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=398&s=30&url=http://events.ctrip.com/eventsale/Vacation/291.html  ',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=398&s=30', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=398&s=30', 
'onloadTrackUrl3rd': '', 
'code': 'success'
},{"adid":"31",'link':'http://pages.ctrip.com/commerce/promote/201309/tz/index1.html',
'src': 'http://images3.c-ctrip.com/rk/201309/smjd5_580X145.jpg',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=516&s=31&url=http://pages.ctrip.com/commerce/promote/201309/tz/index1.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=516&s=31', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=516&s=31', 
'onloadTrackUrl3rd': '', 
'code': 'success'
},{"adid":"32",'link':'http://events.ctrip.com/eventsale/218qizhugaoxingjiudian.html',
'src': 'http://images3.c-ctrip.com/rk/201307/gxrz580145.jpg ',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=515&s=32&url=http://events.ctrip.com/eventsale/218qizhugaoxingjiudian.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=515&s=32', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=515&s=32', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"allyesId2":[{"adid":"33",'link':'http://pages.ctrip.com/commerce/promote/201309/other/cls/cls01a.html',
'src': 'http://images3.c-ctrip.com/rk/201309/gwe_580x145a.jpg',
'width' : 580,
'height' : 145,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=543&s=33&url=http://pages.ctrip.com/commerce/promote/201309/other/cls/cls01a.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=543&s=33', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=543&s=33', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic1":[{"adid":"34",'link':'http://pages.ctrip.com/commerce/promote/201309/hotel/ky/ky.html',
'src': 'http://images3.c-ctrip.com/rk/201309/dh.gif',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=542&s=34&url=http://pages.ctrip.com/commerce/promote/201309/hotel/ky/ky.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=542&s=34', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=542&s=34', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic2":[{"adid":"40",'link':'http://you.ctrip.com/special/hawaii.aspx',
'src': 'http://images4.c-ctrip.com/target/tg/728/281/861/44ab7986420a4f81a36a0e4208cb2bb9.jpg',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=531&s=40&url=http://you.ctrip.com/special/hawaii.aspx',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=531&s=40', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=531&s=40', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic3":[{"adid":"41",'link':'http://pages.ctrip.com/commerce/promote/201308/vacation/jqdc/jqdc_bj.html',
'src': 'http://images3.c-ctrip.com/dj/201308/jqdc_16070.jpg',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=326&s=41&url=http://pages.ctrip.com/commerce/promote/201308/vacation/jqdc/jqdc_bj.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=326&s=41', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=326&s=41', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic4":[{"adid":"42",'link':'http://pages.ctrip.com/commerce/promote/201307/hotel/pf/index.html',
'src': 'http://images3.c-ctrip.com/rk/201307/pfxy.jpg',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=208&s=42&url=http://pages.ctrip.com/commerce/promote/201307/hotel/pf/index.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=208&s=42', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=208&s=42', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic5":[{"adid":"43",'link':'http://pages.ctrip.com/commerce/promote/201205/flight/yysj/index.html',
'src': 'http://images3.c-ctrip.com/rk/201306/a160x7004.jpg',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=209&s=43&url=http://pages.ctrip.com/commerce/promote/201205/flight/yysj/index.html',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=209&s=43', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=209&s=43', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}],"gg_pic6":[{"adid":"44",'link':'http://pages.ctrip.com/commerce/promote/201309/vacation/gcjq/gcjq_bj.html ',
'src': 'http://images3.c-ctrip.com/dj/201308/jqdc_16070.jpg  ',
'width' : 160,
'height' : 70,
'clickTrackUrl' : 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=3&a=540&s=44&url=http://pages.ctrip.com/commerce/promote/201309/vacation/gcjq/gcjq_bj.html ',
'onloadTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=1&a=540&s=44', 
'onloadVTrackUrl': 'http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&t=2&a=540&s=44', 
'onloadTrackUrl3rd': '', 
'code': 'success'
}]};var G_adTrackUrl="http://crm.ws.ctrip.com/Customer-Market-Proxy/AdCallProxy.aspx?re=adt&adtlist=%5b%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22189%22%2c%22adLoationZt%22%3a%2227%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22539%22%2c%22adLoationZt%22%3a%2228%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22523%22%2c%22adLoationZt%22%3a%2229%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22398%22%2c%22adLoationZt%22%3a%2230%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22516%22%2c%22adLoationZt%22%3a%2231%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22515%22%2c%22adLoationZt%22%3a%2232%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22543%22%2c%22adLoationZt%22%3a%2233%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22542%22%2c%22adLoationZt%22%3a%2234%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22531%22%2c%22adLoationZt%22%3a%2240%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22326%22%2c%22adLoationZt%22%3a%2241%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22208%22%2c%22adLoationZt%22%3a%2242%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22209%22%2c%22adLoationZt%22%3a%2243%22%7d%2c%7b%22trackType%22%3a%221%22%2c%22ztID%22%3a%22540%22%2c%22adLoationZt%22%3a%2244%22%7d%5d";;window.replace=function(){return ''};function isCanvasSupported(){var a=document.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))}function reloadConfig(a){var b=1,d=[],c;for(c in a)for(var e=0;e<a[c].length;e++)"success"!=a[c][e].code&&(b=0,d.push(c+"-"+e));0==b&&ctripAds.loadJs(g_adsconfig + "?2013-9-24.js");return b;}var ctripAds=ctripAds||{};if(ctripAds.isInit){reloadConfig(G_adContentConfig);ctripAds.imgOnloadCallback(G_adContentConfig);ctripAds.updateConfig(G_adContentConfig);}else{ctripAds.init=function(a){if(reloadConfig(a)){ctripAds.isInit=!0;if(0==a.length)return!1;ctripAds.initCss();ctripAds.queue={};ctripAds.isLoadMobileAd=!1;ctripAds.mutliAdsName="";ctripAds.browser={};ctripAds.browser.isHtml5=isCanvasSupported();ctripAds.browser.isFilterSupported="filters"in document.body;ctripAds.browser.isIE=(/msie (\d+)/).test(navigator.userAgent.toLowerCase());ctripAds.imgOnloadCallback(a);for(var b in a){var d=new ctripSingleAd(b,a[b]);ctripAds.queue[b]=d}}};ctripAds.initCss=function(){var a=document.createElement("style");a.type="text/css";("undefined"!=typeof a.styleSheet?a.styleSheet.cssText=".j-picsroller{position:relative; z-index:1;filter :progid:DXImageTransform.Microsoft.Fade(duration=0.5);}			.j-picsroller-pics{margin: 0;padding:0;}			.j-picsroller-pics a{text-decoration:none;}			.j-picsroller-pics img{border:none;vertical-align:middle;}			.j-picsroller-numbox{position:absolute;z-index:8;bottom:10px;width: 100%;}			.j-picsroller-num{height: 15px; list-style: none;margin: 0 auto;max-width: 1180px;overflow: hidden;padding: 0;text-align: right;}			.j-picsroller-num li{display:inline-block;*display:inline;*zoom:1; overflow:hidden;width:11px;height:11px;margin-right:8px;border:2px solid #FFFFFF;border-radius:11px 11px 11px 11px;cursor:pointer;list-style:none;background-color:#0AB0E8;}			.j-picsroller-num li.j-num-current {background-color:#F8CD47;cursor:pointer;}			.j-ani-out{-webkit-animation:fadeOut 2s .2s ease both;-moz-animation:fadeOut 2s .2s ease both;-o-animation:fadeOut 2s .2s ease both;-ms-animation:fadeOut 2s .2s ease both;animation:fadeOut 2s .2s ease both;}			    @-webkit-keyframes fadeOut{0%{opacity:1;}100%{opacity:0;}}			    @-moz-keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			    @-o-keyframes fadeOut{0%{opacity:1;}100%{opacity:0;}}			    @-ms-keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			    @keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			.j-ani-in{ -webkit-animation:fadeIn 2s .2s ease both; -moz-animation:fadeIn 2s .2s ease both; -o-animation:fadeIn 2s .2s ease both; -ms-animation:fadeIn 2s .2s ease both; animation:fadeIn 2s .2s ease both; }			    @-webkit-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-moz-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-o-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-ms-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}":(a.innerHTML=".j-picsroller{position:relative; z-index:1;filter :progid:DXImageTransform.Microsoft.Fade(duration=0.5);}			.j-picsroller-pics{margin: 0;padding:0;}			.j-picsroller-pics a{text-decoration:none;}			.j-picsroller-pics img{border:none;vertical-align:middle;}			.j-picsroller-numbox{position:absolute;z-index:8;bottom:10px;width: 100%;}			.j-picsroller-num{height: 15px; list-style: none;margin: 0 auto;max-width: 1180px;overflow: hidden;padding: 0;text-align: right;}			.j-picsroller-num li{display:inline-block;*display:inline;*zoom:1; overflow:hidden;width:11px;height:11px;margin-right:8px;border:2px solid #FFFFFF;border-radius:11px 11px 11px 11px;cursor:pointer;list-style:none;background-color:#0AB0E8;}			.j-picsroller-num li.j-num-current {background-color:#F8CD47;cursor:pointer;}			.j-ani-out{-webkit-animation:fadeOut 2s .2s ease both;-moz-animation:fadeOut 2s .2s ease both;-o-animation:fadeOut 2s .2s ease both;-ms-animation:fadeOut 2s .2s ease both;animation:fadeOut 2s .2s ease both;}			    @-webkit-keyframes fadeOut{0%{opacity:1;}100%{opacity:0;}}			    @-moz-keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			    @-o-keyframes fadeOut{0%{opacity:1;}100%{opacity:0;}}			    @-ms-keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			    @keyframes fadeOut{ 0%{ opacity:1; } 100%{ opacity:0; }}			.j-ani-in{ -webkit-animation:fadeIn 2s .2s ease both; -moz-animation:fadeIn 2s .2s ease both; -o-animation:fadeIn 2s .2s ease both; -ms-animation:fadeIn 2s .2s ease both; animation:fadeIn 2s .2s ease both; }			    @-webkit-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-moz-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-o-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @-ms-keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}			    @keyframes fadeIn{ 0%{ opacity:0; } 100%{ opacity:1; }}"));document.getElementsByTagName("head")[0].appendChild(a)};ctripAds.updateConfig=function(a){for(var b in a)ctripAds.queue[b].updateConfig(a[b])};ctripAds.loadJs=function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};ctripAds.imgLoad=function(a,b,d){b.onload=function(){for(var b=0;b<d.length;b++)a[d[b]]&&((new (Image)).src=a[d[b]])}};ctripAds.imgOnloadCallback=function(a){var b=0;"undefined"!==typeof G_adTrackUrl&&((new (Image)).src=G_adTrackUrl,b=1);for(var d in a){var c=a[d];if(0<c.length)for(var e=0,f=c.length;e<f;e++){var g=c[e];if("success"==g.code){var h=new (Image);h.src=g.src;(1===b?ctripAds.imgLoad(g,h,["onloadTrackUrl3rd"]):ctripAds.imgLoad(g,h,["onloadTrackUrl","onloadTrackUrl3rd"]))}}}};var ctripSingleAd=function(a,b){this.dom=document.getElementById(a);this.config=b;this.init()};ctripSingleAd.prototype={init:function(){this.mod=(1==this.config.length?"single":"multi");this.lastIndex=-1;this.currentIndex=0;this.lastDomIndex=1;this.genHtml();"multi"==this.mod&&this.setEffect()},updateConfig:function(a){if("single"==this.mod&&"success"==a[0].code)this.updateSingleAd(this.dom_ads[0],this.dom_img[0],a[0]);else for(var b=0,d=a.length;b<d;b++)"success"==a[b].code&&(this.config[b]=a[b])},genHtml:function(){var a=this.config;this.dom.className+=" j-picsroller";var b=['<div class="j-picsroller-pics">'],d=[];if(0==a.length)return!1;if("single"==this.mod){var c=a[0];b.push('<a href="'+c.link+'" target="_blank" data-ct="'+c.clickTrackUrl+'" data-adid="'+c.adid+'">					<img src="'+c.src+'" width="'+c.width+'" height="'+c.height+'">					</a>')}else{for(var e,d=['<div class="j-picsroller-numbox"><ul class="j-picsroller-num" >'],f=0,g=a.length;f<g;f++)c=a[f],e="",2>f&&(ctripAds.browser.isFilterSupported?0==f&&(c='<a href="'+c.link+'" target="_blank" style="position:absolute;z-index:'+(a.length-f)+";"+e+';" data-ct="'+c.clickTrackUrl+'" data-ct="'+c.clickTrackUrl+'"  data-adid="'+c.adid+'">									<img src="'+c.src+'" width="'+c.width+'" height="'+c.height+'">									</a>',b.push(c)):(ctripAds.browser.isHtml5?(c='<a href="'+c.link+'" target="_blank" style="position:absolute;z-index:'+(a.length-f)+";"+e+';" data-ct="'+c.clickTrackUrl+'"  data-adid="'+c.adid+'">									<img src="'+c.src+'" width="'+c.width+'" height="'+c.height+'">									</a>',b.push(c)):0==f&&(c='<a href="'+c.link+'" target="_blank" style="position:absolute;z-index:'+(a.length-f)+";"+e+';" data-ct="'+c.clickTrackUrl+'" data-ct="'+c.clickTrackUrl+'"  data-adid="'+c.adid+'">									<img src="'+c.src+'" width="'+c.width+'" height="'+c.height+'">									</a>',b.push(c)))),d.push("<li data-index='"+f+"' class="+(0==f?"j-num-current":"")+"></li>");d.push("</ul></div>")}b.push("</div>");this.dom.innerHTML=b.join("")+d.join("");this.dom.style.background="none";this.dom_img=this.dom.getElementsByTagName("IMG");this.dom_ads=this.dom.getElementsByTagName("A");this.dom_dots=this.dom.getElementsByTagName("LI");this.bindEvent()},bindEvent:function(){var a=this;this.dom.onclick=function(b){b=window.event||b;b=b.target||b.srcElement;("LI"==b.tagName?(b=b.getAttribute("data-index"),a.gotoAd(parseInt(b,10))):"IMG"==b.tagName&&ctripAds.loadJs(b.parentNode.getAttribute("data-ct")))}},setEffect:function(){var a=this;this.timer=setTimeout(function(){a.gotoAd()},5E3)},updateSingleAd:function(a,b,d){a.href=d.link;a.setAttribute("data-ct",d.clickTrackUrl);a.setAttribute("data-adid",d.adid);b.src=d.src;b.style.width=d.width;b.style.height=d.height},gotoAd:function(a){clearTimeout(this.timer);this.lastIndex=this.currentIndex;(1<=arguments.length?this.currentIndex=arguments[0]:this.currentIndex++);this.currentIndex>=this.config.length&&(this.currentIndex=0);ctripAds.isLoadMobileAd&&this.sendRequestMobile(this.currentIndex);(ctripAds.browser.isFilterSupported?(this.dom.filters[0].stop(),this.dom.filters[0].apply(),this.updateSingleAd(this.dom_ads[0],this.dom_img[0],this.config[this.currentIndex]),this.dom.filters[0].play()):this.updateSingleAd(this.dom_ads[0],this.dom_img[0],this.config[this.currentIndex]));this.dom_dots[this.currentIndex].className="j-num-current";this.dom_dots[this.lastIndex].className="";this.setEffect()},sendRequestMobile:function(a){if(!G_adContentConfig[ctripAds.mutliAdsName][a].isLoad&&G_adContentConfig[ctripAds.mutliAdsName][a].onloadVTrackUrl){var b=G_adContentConfig[ctripAds.mutliAdsName][a].onloadVTrackUrl;(new (Image)).src=b;G_adContentConfig[ctripAds.mutliAdsName][a].isLoad=!0}}};ctripAds.init(G_adContentConfig)}(function(){var a=G_adContentConfig,b=[],d;for(d in a){var c={},e=document.getElementById(d);c.id=d;c.left=e.offsetLeft;c.right=c.left+a[d][0].width;c.top=(300<a[d][0].width?e.offsetTop:1757);c.bottom=c.top+a[d][0].height;c.isLoad=!1;b.push(c)}var f=f||{};f.checkZone=function(a,b){for(var c=0,d=a.length;c<d;c++)a[c].isLoad||this.checkImgZone(a[c],b)};f.checkImgZone=function(a,b){var c=!0,c=(a.right<b.left?!1:(a.left>b.right?!1:(500<a.right-a.left&&a.bottom+100<b.top?!1:(200>a.right-a.left&&a.bottom<b.top?!1:(a.top>b.bottom?!1:!0)))));100>a.top&&(c?(ctripAds.isLoadMobileAd=!0,ctripAds.mutliAdsName=a.id):ctripAds.isLoadMobileAd=!1);c&&100<a.top&&(this.sendRequest(a),a.isLoad=!0)};f.sendRequest=function(a){if(G_adContentConfig[a.id][0].onloadVTrackUrl){var b=G_adContentConfig[a.id][0].onloadVTrackUrl;a=new (Image);a.src=b}};winSG=window;winSG.onscroll=winSG.onresize=function(){var a={};a.left=(-1!=window.navigator.userAgent.indexOf("Chrome")||-1!=window.navigator.userAgent.indexOf("Safari")?document.body.scrollLeft:document.documentElement.scrollLeft);a.right=a.left+(-1===window.navigator.userAgent.indexOf("MSIE")?window.innerWidth:document.documentElement.offsetWidth);a.top=(-1!=window.navigator.userAgent.indexOf("Chrome")||-1!=window.navigator.userAgent.indexOf("Safari")?document.body.scrollTop:document.documentElement.scrollTop);a.bottom=a.top+(-1===window.navigator.userAgent.indexOf("MSIE")?window.innerHeight:document.documentElement.offsetHeight);f.checkZone(b,a)};winSG.onload=function(){(-1!=window.navigator.userAgent.indexOf("Chrome")||-1!=window.navigator.userAgent.indexOf("Safari")?document.body.scrollTop+=1:document.documentElement.scrollTop+=1)}})();//isok