function _tcTra(){function t(d){var b=d.match(h.pd);if(b!=null)return b[0];b=0;if((b=d.indexOf("/"))>-1)return d.substring(0,b);return d}function r(d){if(!d||d=="")return 1;for(var b=0,c=0,e=d.length-1;e>=0;e--){c=parseInt(d.charCodeAt(e));b=(b<<6&268435455)+c+(c<<14);if((c=b&266338304)!=0)b^=c>>21}return b}function p(d){d=m(a.bd.cookie,d+"="+a.dh,";");if(d!="-")d=d.substring(d.indexOf(".")+1);return d}function m(d,b,c){if(!d||d==""||!b||b==""||!c||c=="")return"-";var e,g="-";e=d.indexOf(b);b=b.indexOf("=")+
1;if(e>-1){c=d.indexOf(c,e);if(c<0)c=d.length;g=d.substring(e+b,c)}return g}function n(d,b,c){var e="";e=d=="longKey"?d+"="+b+";path=/;":d+"="+a.dh+"."+b+";path=/;";if(c!="")e+=c;e+=a.dn;a.bd.cookie=e}function j(d){a.r=d.replace("http://","").replace("https://","");a.fpd=t(d)}function k(d){var b=d.split("."),c=b[b.length-1]*1+1,e=b[b.length-2];d="";for(var g=0;g<b.length-3;g++)d+=b[g]+".";d+=e+"."+a.mt+"."+c;return d}function u(d,b){b+=1;if(!(b>5||d=="")){var c=new Image;c.src=d+"&_v="+b;c.onerror=
function(){window.setTimeout("_tcRequest('"+d+"',"+b+")",1E3);return true}}}function i(d,b){return typeof encodeURIComponent=="function"?b?encodeURI(d):encodeURIComponent(d):escape(d)}function x(){if(a.r=="0"||a.r==""||a.r=="-")return"";var d=a.r.toLowerCase(),b="-";if(d.indexOf("/")>-1){b=d.substring(d.indexOf("/")+1,d.length);if(b.indexOf("?")>-1)b=b.substring(0,b.indexOf("?"))}if(!h.lurl.test(a.fpd)&&a.fpd!=a.tpd){a.cu=0;a.ci=0;return"utmccn=(referral)|utmcsr="+q(a.fpd)+"|utmcct="+q(b)+"|utmcmd=referral"}else return""}
function v(d){if(a.r=="0"||a.r==""||a.r=="-")return"";for(var b=0,c=a.r.toLowerCase(),e,g=0;g<h.osr.length;g++)if(a.fpd.indexOf(h.osr[g])>-1)if((b=c.indexOf("?"+h.okw[g]+"="))>-1||(b=c.indexOf("&"+h.okw[g]+"="))>-1){e=c.substring(b+h.okw[g].length+2,c.length).replace("|","\u2016");if((b=e.indexOf("&"))>-1)e=e.substring(0,b);b="-";if(h.esl[g]!="")b=m(c.substring(c.indexOf("?")+1,c.length),h.esl[g]+"=","&");if(h.eslutf.test(c))b="utf-8";if(b=="-"){b="utf-8";if(h.eslgb.test(h.osr[g]))b="gb2312";switch(h.osr[g]){case "baidu":if(c.indexOf("ssid=0/from=844b")>
0)b="utf-8"}}a.cu=0;a.ci=0;return d?"|utmEsl="+b+"|utmctr="+q(e):"utmccn=(organic)|utmcmd=organic|utmEsl="+b+"|utmcsr="+h.osr[g]+"|utmctr="+q(e)}return""}function q(d){return d.replace(/ /g,"+")}function z(d){if(d=="-"){a.cu=0;a.ci=0}else if(d.indexOf("tckeyword=")>-1){a.cu=d.replace("tckeyword=","");a.ci=0}else{a.cu=d.split(".")[0];a.ci=d.split(".")[1]}}function y(){var d="";d+="&utmn="+Math.round(Math.random()*2147483647);var b;a:{b="";var c="-",e=0,g=0,f=0,l=a.cz;f=a.dlh;c=m(f,h.crf+"=","&");try{c!=
"-"&&c!=""&&j(typeof decodeURIComponent=="function"?decodeURIComponent(c):decodeURI(c))}catch(w){}c=m(f,h.csr+"=","&");if(c!="-"&&c!=""){b="utmcsr="+i(q(c));c=m(f,h.ccn+"=","&");b+=c!="-"&&c!=""?"|utmccn="+i(q(c)):"|utmccn=(not+set)";c=m(f,h.cmd+"=","&");b+=c!="-"&&c!=""?"|utmcmd="+i(q(c)):"|utmcmd=(not+set)";c=v(1);if(c!="-"&&c!="")b+=c;c=m(f,h.cct+"=","&");if(c!="-"&&c!="")b+="|utmcct="+i(q(c))}if(b=="-"||b=="")b=v();if(b=="-"||b=="")b=x();c=m(f,h.ctr+"=","&");a.cu=c!="-"&&c!=""?c:a.cu;c=m(f,h.cti+
"=","&");a.ci=c!="-"&&c!=""?c:a.ci;if(b=="-"||b==""||typeof b=="undefined"){if(l=="-")b="utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)";if(b=="-"||b==""){b="";break a}}if(l!="-"){f=l.indexOf(".");if(f>-1)f=l.indexOf(".",f+1);if(f>-1)f=l.indexOf(".",f+1);c=l.substring(f+1,l.length);if(c.toLowerCase()==b.toLowerCase())e=1;c=l.substring(0,f);if((f=c.lastIndexOf("."))>-1){c=c.substring(f+1,c.length);g=c*1}}if(e==0||a.fns==1){g++;a.cz=a.mt+"."+a.ca.split(".")[a.ca.split(".").length-1]+"."+g+"."+b}b=e==
0||a.fns==1?"&utmcn=1":"&utmcr=1"}d+=b;if(a.bd.title&&a.bd.title!="")d+="&utmdt="+i(a.bd.title);d+="&utmhid="+a.cb.split(".")[0];d+="&utmr="+i(a.r);d+="&utmp="+i(a.hr);if(a.orser!="")d+="&serialid="+a.orser;if(a.pview!="")d+="&Pageview="+i(a.pview);if(a.ck!="")d+="&ClickKey="+i(a.ck);if(a.ckv!="")d+="&ClickValue="+i(a.ckv);d+="&refId="+a.refid+"&userId="+a.uid;d=h.gifpath+"?utmac="+a.acct+d+"&utmcc=";b="";b+=i("__tctma="+a.dh+"."+a.ca+";+");b+=i("__tctmb="+a.dh+"."+a.cb.substring(a.cb.indexOf(".")+
1,a.cb.length)+";+");b+=i("__tctmz="+a.dh+"."+a.cz+";+");b+=i("__tctmu="+a.dh+".tckeyword="+a.cu+"|tcideaid="+a.ci+";");d=d+b+"&bInfo=";e=c=b=g="-";l=1;f="";f=navigator;if(self.screen){g=screen.width+"x"+screen.height;b=screen.colorDepth+"-bit"}else if(self.java){g=java.awt.Toolkit.getDefaultToolkit().getScreenSize();g=g.width+"x"+g.height}if(f.language)c=f.language.toLowerCase();else if(f.browserLanguage)c=f.browserLanguage.toLowerCase();l=f.javaEnabled()?1:0;if(a.bd.characterSet)e=i(a.bd.characterSet);
else if(a.bd.charset)e=i(a.bd.charset);var o=f.userAgent.toLowerCase();f=o.indexOf("metasr")>-1?"sogou":o.indexOf("theworld")>-1?"theworld":o.indexOf("firefox")>-1?"firefox":o.indexOf("chrome")>-1?"chrome":o.indexOf("safari")>-1?"safari":o.indexOf("opera")>-1?"opera":o.indexOf("msie")>-1?"msie":f.appName?f.appName:"other";d+=i("utmcs="+e+";utmsr="+g+";utmsc="+b+";utmul="+c+";utmje="+l+";utmie="+f);u(d,0);a.fns=0;n("__tctmu",a.cu+"."+a.ci,"");a.cz!="-"&&a.cz!=""&&n("__tctmz",a.cz,"")}function B(){var d=
document.createElement("script");d.type="text/javascript";d.src="http://www."+a.fpd+"/vstjsonp/GetCookie.ashx?CookieKey=__tctmu,__tctmz&CallBack=_tcTraObj.CallBack";d.onreadystatechange=d.onerror=function(){if(!this.readyState||(this.readyState==="loaded"||this.readyState==="complete")&&!window[obj])y()};document.getElementsByTagName("head")[0].appendChild(d)}var a={dn:"",acct:"-",bd:document,dm:document.domain,dl:document.location,hr:document.location.href.replace("http://","").replace("https://",
""),ishttps:document.location.protocol=="https:",fpd:"",tpd:"",u:_tclk,mt:_tcmmt,dt:(new Date).getTime(),r:document.referrer,fns:0,dh:0,rc:0,dlh:document.location.search.replace("?",""),orser:"-",pview:"-",refid:0,uid:0,ca:"-",cb:"-",cu:"-",cz:"-",ck:"",ckv:"",ci:"-",hid:Math.round(Math.random()*4503599627370495)},h={ccn:"utm_campaign",cmd:"utm_medium",csr:"utm_source",crf:"utm_referrer",ctr:"tckeywordid",cti:"tcideaid",cct:"utm_content",nb:/^(172.|192.|127.|localhost)/,osr:["baidu","baidu","google",
"sogou","soso","youdao","bing","yahoo","114so","gougou","jike","panguso","360","so"],okw:["wd","word","q","query","w","q","q","p","kw","search","q","q","q","q"],esl:["ie","ie","ie","ie","ie","ue","","ei","","","","","ie","ie"],eslutf:/(m.baidu.com|wap.baidu.com|baidu.mobi|3g.baidu.com|m1.baidu.com|m5.baidu.com)/,eslgb:/^(baidu|soso|sogou|118114)$/,lurl:/(tongcheng.com|17u.cn|17u.com|17u.net|172.|192.|127.0.0.1|localhost)/,gifpath:"http://vstgif.17usoft.com/__tctm.gif",eventpath:"http://vstlog.17usoft.com/TrackEvent/TrackEvent.ashx",
pd:/[\w-]+\.(com|net|org|gov|cc|biz|info|cn|mil|biz|name|rec)(\.(cn|hk|ca|pe))*/,cazz:/^(\d+\.\d+\.\d+\.\d+\.\d+){1}$/,cbzz:/^(\d+\.\d+\.\d+\.\d+){1}$/};this._tcTras=function(){if(a.dl.protocol!="file:")if(!h.nb.test(a.dm)){if(a.ishttps){h.gifpath="https://vstgif.17u.cn/__tctm.gif";h.eventpath="https://vstlog.17usoft.com/TrackEvent.ashx"}if(typeof _owopentime!="undefined")a.ot=(new Date).getTime()-_owopentime;var d=a,b;a.tpd=t(a.dm);a.dn=" domain="+a.tpd;b=r(a.tpd);d.dh=b;if(a.dh>0){if((!a.r||a.r==
"")&&typeof window.opener!="undefined")try{a.r=window.opener.location.href}catch(c){}if(!a.r||a.r=="")a.r="-";else if(a.r.indexOf("[")==0&&a.r.lastIndexOf("]")==a.r.length-1)a.r="-";j(a.r);if(!a.dlh)a.dlh="";if(typeof a.dl.hash!="undefined"&&!a.dl.hash)a.dlh+=a.dl.hash.replace("#","&").replace("?","&");b=" expires="+(new Date(a.dt+63072E6)).toGMTString()+";";d=" expires="+(new Date(a.dt+18E5)).toGMTString()+";";var e,g=0,f=0;a.ca=p("__tctma");a.cb=p("__tctmb");var l=p("__tctmu");a.cz=p("__tctmz");
e=p("__tctmc");if(!h.cazz.test(a.ca)){a.ca=a.u+"."+a.mt+"."+a.mt+"."+a.mt+".1";g=-1}if(!h.cbzz.test(a.cb)){a.cb=a.hid+"."+a.mt+"."+a.mt+".1";f=-1}var w=r(a.hr.toLowerCase()),o=r(a.r.toLowerCase()),A=0;if(g==0&&f==0){g=p("__tctmd");if(e!=w||g!=o){a.cb=k(a.cb);n("__tctmc",w,"");n("__tctmd",o,"")}else A=1}else{if(g==0)a.ca=k(a.ca);a.cb=a.hid+"."+a.mt+"."+a.mt+".1";n("__tctmc",w,"");n("__tctmd",o,"");a.fns=1}z(l);e=A;n("__tctma",a.ca,b);n("__tctmb",a.cb,d);if(e==0){if(typeof _tcq!="undefined"){d="";for(b=
0;b<_tcq.length;b++)if(typeof _tcq[b][1]!="undefined"){d=_tcq[b][0].toLowerCase().replace(/{|\^|}/g,"");e=_tcq[b][1];switch(d){case "_serialid":a.orser=e;break;case "_vrcode":a.acct=e;break;case "_trackpageview":a.pview=e;break;case "_refid":a.refid=e;break;case "_userid":a.uid=e;break;case "_clickkey":a.ck=e;break;case "_clickvalue":a.ckv=e}}}!a.ishttps&&a.fpd!=a.tpd&&h.lurl.test(a.fpd)?B():y()}}n("longKey",a.u,"")}};this.CallBack=function(d){try{if(d){var b=eval(d);b.hasOwnProperty("__tctmu")&&
b.__tctmu.length>0&&z(b.__tctmu.substr(b.__tctmu.indexOf(".")+1));if(b.hasOwnProperty("__tctmz")&&b.__tctmz.length>0){var c=b.__tctmz.indexOf(".");if(c>-1)c=b.__tctmz.indexOf(".",c+1);if(c>-1)c=b.__tctmz.indexOf(".",c+1);if(c>-1)c=b.__tctmz.indexOf(".",c+1);var e=b.__tctmz.substring(c+1,b.__tctmz.length);if(a.cz=="-")e=a.mt+"."+a.ca.split(".")[a.ca.split(".").length-1]+".1."+e;else{c=a.cz.indexOf(".");d=0;if(c>-1)c=a.cz.indexOf(".",c+1);if(c>-1)c=a.cz.indexOf(".",c+1);var g=a.cz.substring(0,c);if((c=
g.lastIndexOf("."))>-1){g=g.substring(c+1,g.length);d=g*1}e=a.mt+"."+a.ca.split(".")[a.ca.split(".").length-1]+"."+d+"."+e}a.cz=e}}}catch(f){}y()};this._tcTrackEvent=function(d,b,c,e,g){if(!(!d||d==""||!b||b=="")){var f="{";if(!g||g=="")g=a.hr;f+='"LoginKey":'+a.ca.split(".")[0]+"";f+=',"LoginCount":'+a.ca.split(".")[4]+"";f+=',"SessionId":'+a.cb.split(".")[0]+"";f+=',"PageCount":'+a.cb.split(".")[3]+"";f+=',"Category":"'+i(d)+'"';f+=',"Action":"'+i(b)+'"';f+=',"FromPage":"'+i(g)+'"';f+=',"Label":"'+
(c&&c!=""?i(c):"")+'"';f+=',"Value":"'+(e&&e!=""?i(e):"")+'"';f+="}";u(h.eventpath+"?TrackEvent="+f,0)}}}
function _tcMdEvent(){var t=null,r=true,p=function(j){if(r==false||parseInt(Math.random()*100)>_tcHotmapx.sp)return false;r=false;t&&clearTimeout(t);t=setTimeout(function(){r=true},500);j=m(j);return"http://vstlog.17usoft.com/heatmap/ClickStream.ashx?rx="+(j.x-parseInt(n()/2,10))+"&ry="+j.y+"&pid="+_tcHotmapx.pid+"&dt="+(new Date).getTime()},m=function(j){j=j||window.event;return{x:j.pageX||j.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),y:j.pageY||j.clientY+(document.documentElement.scrollTop||
document.body.scrollTop)}},n=function(){var j,k;if(window.innerWidth&&window.scrollMaxX)j=window.innerWidth+window.scrollMaxX;else if(document.body.scrollHeight>document.body.offsetHeight)j=document.body.scrollWidth;else if(document.body)j=document.body.offsetWidth;if(window.innerWidth)k=window.innerWidth;else if(document.documentElement&&document.documentElement.clientWidth)k=document.documentElement.clientWidth;else if(document.body)k=document.body.clientWidth;return j<k?k:j};this._mdEvent=function(j){typeof _tcHotmapx==
"undefined"||!_tcHotmapx||function(k,u,i){if(k.addEventListener)k.addEventListener(u,i,false);else if(k.attachEvent){var x=function(v){return function(){i.call(v)}}(k);k.attachEvent("on"+u,x)}}(j,"mousedown",function(k){if(k=p(k)){s=document.createElement("script");s.language="javaScript";s.type="text/JavaScript";s.src=k;document.getElementsByTagName("head")[0].appendChild(s)}})}}(function(){_tcTraObj=new _tcTra;_tcTraObj._tcTras();(new _tcMdEvent)._mdEvent(document)})();
