/*from tccdn minify at 2013-12-26 15:58:48,file：/cn/c/s/2013/searchNew.0.1.0.js*/
function getWeekCommon(a){var a=fish.parseTime(a),c,f=["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],d=fish.parseTime(new Date()),e=fish.parseTime(new Date(),{days:1}),b=fish.parseTime(new Date(),{days:2});switch(a){case d:return c="今天";break;case e:return c="明天";break;case b:return c="后天";break;default:return c=f[fish.parseDate(a).getDay()];break}}function validaClick(g,f,h){if(h){var c=document.getElementById(f);if(c){if(c.style.display==""||c.style.display=="inline"||c.style.display=="block"){var d=fish.getTarget(g);rt=false;if(d.id==f||d.id==h){rt=true}else{while(d&&d.localName!="body"){d=d.parentNode;if(d!=null){if(d.id==f||d.id==h){rt=true;break}}}}if(!rt){c.style.display="none"}}}}else{validaClick1(g,f)}}function validaClick1(f,h){var c=document.getElementById(h[0]);if(c){if(c.style.display==""||c.style.display=="inline"||c.style.display=="block"){var d=fish.getTarget(f);rt=false;for(var g=0;g<h.length;g++){if(d.id==h[g]){rt=true}}if(!rt){while(d&&d.localName!="body"){d=d.parentNode;if(d!=null){for(var g=0;g<h.length;g++){if(d.id==h[g]){rt=true;break}}}}}if(!rt){c.style.display="none"}}}}function splitData(b){var e="split|,|split";var g="split|:|split";var d=b.split(e);var a=[];if(d!=null&&d.length>0){for(var c=0;c<d.length;c++){var f=d[c].split(g);if(f!=null&&f.length==2){a.push(f[1])}}return a}}function iflightMoreLine(){if(fish.one("#top_airplane").hasClass("atop_airplane")&&fish.one("div.trayAir div.need_btn_search").hasClass("need_btn_dc")&&fish.one("#isearchIfligt").hasClass("airpInter")){fish.one("#soso_17u").css("width:851px;height:auto;")}else{fish.one("#soso_17u").css("width:490px;")}}fish.ready(function(){var e=fish.one("#diysearchpara").val(),d=false;fish.one("#soso_17u").mTab({tab:".search_left a",normal:"nor",replace:"hotel_at",content:".tray",cookieName:"soso_17u_tab_open_index",aliveTime:{days:7},init:function(){fish.one("#soso_17u").css("width:490px;");var f=fish.cookie.get("soso_17u_tab_open_index");if(!f){fish.dom("#top_hotel")._added_=true;fish.ajax({url:"script/searchHotel.0.0.9.js?v=2013101102",type:"script"})}},fn:function(i,f){fish.all(i).addClass(("a"+i[0].id));iflightMoreLine();if(!i[0]._added_){i[0]._added_=true;var j=i[0].id;
switch(j){
case"top_hotel":fish.ajax({url:"script/searchHotel.0.0.9.js?v=2013101102",type:"script"});break;
case"top_airplane":fish.ajax({url:"script/searchFlight.0.0.5.js?v=2013112806",type:"script"});break;
case"top_scenic":fish.ajax({url:"script/searchScence.0.0.2.js?v=2013091001",type:"script"});
//var g=fish.dom("#searchbox-scenery-destination").id,h=fish.dom("#searchbox-scenery-tj").id;fish.ajax({url:"data/AsyncHandler.ashx?"+e+"&idlist="+g+","+h,ajaxType:"string",fn:function(k){var l=splitData(k);fish.one("#seSceDes").html(l[0]);fish.one("#seSceTj").html(l[1])}});break;
case"top_selftrip":fish.ajax({url:"script/searchSelf.0.0.5.js?v=2013091001",type:"script"});var g=fish.dom("#searchbox-self-hotsearchnew").id;fish.ajax({url:"data/AsyncHandler.ashx?"+e+"&idlist="+g,ajaxType:"string",fn:function(k){var l=splitData(k);fish.one("#searchbox-self-hotsearchnew").html("remove");fish.one(".tab_self_con table").html("after",l[0])}});break;
case"top_abroad":fish.ajax({url:"script/searchAbroad.0.0.2.js?v=2013091001",type:"script"});break;
case"top_phone":fish.ajax({url:"script/searchPhone.0.0.4.js?v=2013102401",type:"script"});break
}
}}});var a=fish.one("#tab_top_airplane .airplaneDiv"),b;a.mTab({tab:".airplane_tab a",normal:"nor",replace:"airpInter",content:".trayAir",fn:function(g,f){iflightMoreLine();if(!g[0]._added_){g[0]._added_=true;var h=g[0].id;switch(h){case"isearchIfligt":clearTimeout(b);b=setTimeout(function(){fish.ajax({url:"script/searchIFlight.0.0.5.js?v=2013091001",type:"script"})},0);break;default:break}}}});fish.all(".search_btn").hover(function(){fish.one(this).addClass("search_btnHover")},function(){fish.one(this).removeClass("search_btnHover")});if(fish.all("#soso_17u .input02").length>0){var c=false;fish.all("#soso_17u .input02").hover(function(){if(!c){fish.one(this).addClass("inputHover")}},function(){if(!c){fish.one(this).removeClass("inputHover")}});fish.all("#soso_17u .input02").on("focus",function(){fish.one(this).addClass("inputHover");c=true});fish.all("#soso_17u .input02").on("blur",function(){fish.one(this).removeClass("inputHover");c=false})}});